### ISSUE TITLE
secrets.py should not be overwritten point blank

### ISSUE THREAD

**Issue by mathcolo** [transitmatters/new-train-tracker#98]
@z0glen made a delightful change to permit NTT to run without an adjacent PostgreSQL server. That included a secrets.py modification, which the CD job overwrote on merge with the instance copy. I added Zach's change to said copy, but ideally the key would be patched in (or read from env? or elsewhere?)

**Comment by nathan-weinberg** [comment]
CD doesn't overwrite `secrets.py` - we copy a local version defined in a separate location on the instance into the newly-cloned repo to restore the information in the file we don't want pushed to GitHub. Instead of doing convoluted merging/patching of files, perhaps we should instead alter the app to consume these "secrets" as environmental variables, which makes more sense than using a Python file as a data store.
